name: PreProd Deployment

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate PreProd deployment
        run: |
          echo "Deploying application to PreProd..."
          echo "PreProd deployment successful"