name: PreProd Deployment

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate PreProd deployment
        run: |
          echo "Deploying application to PreProd..."
          echo "PreProd deployment successful"

      - name: Trigger Playwright test repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_REPO_TOKEN }}" \
            https://api.github.com/repos/kaushal0212/playwright-test-CI-CD/dispatches \
            -d '{"event_type":"run-preprod-tests-Event"}'